FROM ubuntu:14.04.4
ENV DEBIAN_FRONTEND noninteractive
RUN sed -i "s/archive.ubuntu.com/us.archive.ubuntu.com/g" /etc/apt/sources.list
RUN echo "deb [trusted=yes] http://{{ ansible_default_ipv4['address'] }}:8888/contrail amd64/" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y --force-yes contrail-utils python-contrail python-contrail-vrouter-api \
                                   git python-pip python-yaml
RUN git clone https://github.com/michaelhenkel/opencontrail-docker-libnetwork.git /opencontrail-docker-libnetwork
RUN pip install netaddr pyroute2 uhttplib
COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]

CMD ["/usr/bin/python","/opencontrail-docker-libnetwork/opencontrail-libnetwork-driver.py","-f","/opencontrail-docker-libnetwork//opencontrail.conf"]
