FROM ubuntu:14.04.4
ENV DEBIAN_FRONTEND noninteractive
RUN sed -i "s/archive.ubuntu.com/us.archive.ubuntu.com/g" /etc/apt/sources.list
RUN echo "deb [trusted=yes] http://{{ ansible_default_ipv4['address'] }}:8888/contrail amd64/" >> /etc/apt/sources.list
RUN apt-get update
RUN mkdir -p /etc/contrail
RUN mkdir -p /var/log/contrail
RUN apt-get install -y --force-yes ifmap-server
COPY entrypoint.sh /
COPY openstack-config /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/sh","/usr/bin/ifmap-server"]
